apiVersion: apps/v1
kind: Deployment
metadata:
  name: before
  annotations:
    argocd.argoproj.io/hook: PreSync
spec:
  selector:
    matchLabels:
      app: hook-app
  replicas: 1
  template:
    metadata:
      labels:
        app: hook-app
    spec:
      containers:
      - name: hook-app
        image: nginx:latest
        ports:
        - containerPort: 80

