apiVersion: apps/v1
kind: Deployment
metadata:
  name: before
  annotations:
    argocd.argoproj.io/hook: PreSync
spec:
  template:
    spec:
      containers:
      - name: sleep
        image: nginx:latest
        ports:
        - containerPort: 80

